export const FETCH_COUNTRY_REQUEST = 'FETCH_COUNTRY_REQUEST';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';
export const FETCH_COUNTRY_GDP_REQUEST = 'FETCH_COUNTRY_GDP__REQUEST';
export const FETCH_COUNTRY_GDP_SUCCESS = 'FETCH_COUNTRY_GDP_SUCCESS';
export const FETCH_COUNTRY_GDP_END = 'FETCH_COUNTRY_GDP_END';
export const FETCH_COUNTRY_GDP_FAILURE = 'FETCH_COUNTRY_GDP_FAILURE';
